spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASS:password}
    url: ${DB_URL:jdbc:mysql://localhost:3306/proposta}

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

analise:
  url: http://localhost:9999

management:
  endpoint:
    health: true