spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASS:password}
    url: ${DB_URL:jdbc:mysql://localhost:3306/proposta}

  jpa:
    show-sql: false

    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/nosso-cartao}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/nosso-cartao/protocol/openid-connect/certs}

analise:
  url: ${ANALISE_URL:http://localhost:9999}

cartao:
  url: ${CARTAO_URL:http://localhost:8888}

feign:
  hystrix:
    enabled: true

period:
  execute: ${PERIOD:1000}

management:
  health:
    probes:
      enabled: ${ENABLE_HEALTHCHECK_PROBES:true}

  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:info,health,prometheus}
    prometheus:
      enabled: ${PROMETHEUS_ENABLED:true}